import { Dimensions, Platform, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#E5E7EB" },
  scrollViewRoot: { flex: 1 },
  container: { alignItems: "center", paddingVertical: 32, minHeight: "100%", paddingBottom: 36 },
  circle: { position: "absolute" },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    width: "90%",
    marginBottom: 32,
    marginTop: 12,
    zIndex: 2,
    justifyContent: "space-between",
  },
  titleContainer: { flex: 1, alignItems: "center" },
  quizzycusTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#374151",
    textAlign: "center",
    letterSpacing: 2,
    backgroundColor: "transparent",
    paddingHorizontal: 8,
    fontFamily: "DynaPuff",
  },
  progressContainer: { alignItems: "center", marginBottom: 12, width: "80%" },
  progressBarBg: {
    height: 16,
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  progressBarFill: { height: "100%", backgroundColor: "#4F46E5", borderRadius: 8 },
  levelText: { marginTop: 8, fontSize: 16, color: "#374151", fontWeight: "bold" },
  coinsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    marginTop: 16,
    justifyContent: "center",
    width: "90%",
  },
  coinIcon: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  coinLetter: {
    color: "#F59E0B",
    fontWeight: "bold",
    fontSize: 20,
    fontFamily: "SourGummy",
  },
  coinCount: { fontSize: 18, fontWeight: "bold", marginLeft: 10, marginRight: 10 },
  buyCoinsButton: {
    backgroundColor: "#F59E0B",
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 24,
    minWidth: 110,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  buyCoinsText: { color: "#F9FAFB", fontWeight: "bold", fontSize: 16 },
  buttonStack: { width: "90%", marginTop: 24, marginBottom: 24, alignItems: "center" },
  menuButton: {
    width: "100%",
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    flexDirection: "row",
    position: "relative",
  },
  menuButtonText: { fontSize: 18, fontWeight: "bold", textAlign: "center" },
  activeUsersScroll: {
    width: "100%",
    marginTop: 8,
    marginBottom: 10,
    minHeight: 120,
    paddingBottom: 10,
  },
  activeUsers: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    minHeight: 120,
  },
  friendSquare: {
    width: 76,
    height: 100,
    backgroundColor: "#F9FAFB",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
    position: "relative",
    marginBottom: 8,
    marginTop: 8,
    ...Platform.select({
      ios: { shadowColor: "#6366F1", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 5 },
      android: { elevation: 4 },
    }),
  },
  friendImage: {
    width: 54,
    height: 54,
    borderRadius: 27,
    marginBottom: 6,
    marginTop: 4,
    borderWidth: 2,
    borderColor: "#6366F1",
  },
  friendName: {
    fontWeight: "bold",
    fontSize: 13,
    color: "#6366F1",
    textAlign: "center",
    fontFamily: "SourGummy",
  },
  onlineDot: {
    position: "absolute",
    width: 12,
    height: 12,
    borderRadius: 6,
    borderColor: "#F9FAFB",
    borderWidth: 2,
  },
  noFriendsContainer: {
    justifyContent: "center",
    alignItems: "center",
    height: 76,
    width: 160,
  },
  noFriendsText: {
    color: "#DC2626",
    fontWeight: "bold",
    fontSize: 17,
    fontFamily: "SourGummy",
  },
  userSquare: {
    backgroundColor: "#E5E7EB",
    width: 54,
    height: 54,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 6,
    borderWidth: 3,
    borderColor: "#DC2626",
  },
  friendsHeading: {
    width: "90%",
    fontSize: 21,
    fontWeight: "bold",
    color: "#6366F1",
    fontFamily: "DynaPuff",
    marginBottom: 0,
    marginTop: 8,
    textAlign: "left",
    alignSelf: "flex-start",
    paddingLeft: 12,
  },
  popupOverlay: {
    flex: 1,
    backgroundColor: "rgba(34, 34, 34, 0.25)",
    justifyContent: "center",
    alignItems: "center",
  },
  friendPopup: {
    width: width * 0.84,
    backgroundColor: "#E5E7EB",
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    padding: 28,
    position: "relative",
    ...Platform.select({
      ios: { shadowColor: "#6366F1", shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.18, shadowRadius: 12 },
      android: { elevation: 7 },
    }),
  },
  popupImage: {
    width: 92,
    height: 92,
    borderRadius: 46,
    marginBottom: 14,
    borderWidth: 3,
    borderColor: "#6366F1",
    alignSelf: "center",
  },
  popupName: {
    fontWeight: "bold",
    fontSize: 22,
    color: "#4F46E5",
    textAlign: "center",
    fontFamily: "SourGummy",
    marginBottom: 18,
    alignSelf: "center",
  },
  popupProgressBarBg: {
    height: 14,
    width: "90%",
    backgroundColor: "#FFFFFF",
    borderRadius: 7,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 8,
    alignSelf: "center",
  },
  popupProgressBarFill: { height: "100%", backgroundColor: "#4F46E5", borderRadius: 7 },
  popupLevel: {
    fontSize: 17,
    color: "#4F46E5",
    fontWeight: "bold",
    fontFamily: "SourGummy",
    textAlign: "center",
    marginBottom: 18,
    alignSelf: "center",
  },
  popupChallengeBtn: {
    backgroundColor: "#16A34A",
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 12,
    alignSelf: "center",
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  popupChallengeText: {
    color: "#FFFFFF",
    fontWeight: "bold",
    fontSize: 18,
    fontFamily: "SourGummy",
    textAlign: "center",
    marginRight: 2,
  },
  popupCloseBtn: { position: "absolute", right: 16, top: 16, zIndex: 2, padding: 6 },
  shareOverlay: {
    flex: 1,
    backgroundColor: "rgba(34, 34, 34, 0.25)",
    justifyContent: "center",
    alignItems: "center",
  },
  sharePopup: {
    width: width * 0.7,
    backgroundColor: "#F9FAFB",
    borderRadius: 22,
    paddingVertical: 30,
    paddingHorizontal: 24,
    alignItems: "center",
    position: "relative",
    ...Platform.select({
      ios: { shadowColor: "#6366F1", shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.12, shadowRadius: 14 },
      android: { elevation: 7 },
    }),
  },
  shareTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#6366F1",
    marginBottom: 18,
    fontFamily: "SourGummy",
    textAlign: "center",
  },
  shareStack: { flexDirection: "column", alignItems: "center", justifyContent: "center" },
  shareIconBtn: {
    marginVertical: 8,
    alignItems: "center",
    justifyContent: "center",
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#E5E7EB",
  },
  shareCloseBtn: { position: "absolute", right: 16, top: 16, zIndex: 2, padding: 6 },
});

export default styles;