import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E5E7EB',
  },
  circle: {
    position: 'absolute',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 56,
    paddingHorizontal: 24,
    justifyContent: 'space-between',
    marginBottom: 38,
    zIndex: 2,
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
  },
  quizzycusTitle: {
    fontSize: 38,
    fontWeight: 'bold',
    letterSpacing: 2,
    textAlign: 'center',
    backgroundColor: 'transparent',
    paddingHorizontal: 8,
    fontFamily: 'DynaPuff',
  },
  buttonsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
    zIndex: 2,
  },
  facebookButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4338CA',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 14,
    marginBottom: 20,
    width: '80%',
    justifyContent: 'center',
    shadowColor: '#4338CA',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.13,
    shadowRadius: 12,
    elevation: 4,
  },
  facebookText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 18,
    marginLeft: 12,
    fontFamily: 'SourGummy',
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 14,
    marginBottom: 20,
    width: '80%',
    justifyContent: 'center',
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.09,
    shadowRadius: 10,
    elevation: 3,
  },
  googleText: {
    fontWeight: 'bold',
    fontSize: 18,
    marginLeft: 12,
    flexDirection: 'row',
    alignItems: 'center',
    fontFamily: 'SourGummy',
  },
  googleTextRow: {
    flexDirection: 'row',
    fontWeight: 'bold',
    fontSize: 18,
    fontFamily: 'SourGummy',
  },
  guestButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#A79696',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 14,
    width: '80%',
    justifyContent: 'center',
    shadowColor: '#A79696',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.11,
    shadowRadius: 8,
    elevation: 2,
  },
  guestText: {
    color: '#F9FAFB',
    fontWeight: 'bold',
    fontSize: 18,
    marginLeft: 12,
    fontFamily: 'SourGummy',
  },
  icon: {
    marginRight: 8,
  },
});

export default styles;